Repository team-warrr/warrr-ui, pull requests merged in 2024-08, with the labels that each got.

#57 feat/#54 패키지 매니저 버전 강제하도록 설정
  .npmrc
  package.json
  pnpm-lock.yaml
Labels: 🛠️ 버그 해결

#43 chore/#37 jest 설정
  .husky/pre-commit
  jest.config.ts
  package.json
  packages/primitive/components/Button.test.tsx
  packages/primitive/components/Button.tsx
  packages/primitive/components/button.css
  pnpm-lock.yaml
Labels: ⚙️ 세팅

#42 feat/#12 Primitive UI codegen 세팅
  .prettierignore
  package.json
  packages/primitive/components/Header.stories.ts
  packages/primitive/components/Header.tsx
  packages/primitive/components/header.css
  pnpm-lock.yaml
  tsconfig.json
  turbo/.gitkeep
  turbo/generators/config.ts
  turbo/generators/templates/component/README.md.hbs
  turbo/generators/templates/component/__tests__/{{kebabCase componentName}}.test.tsx.hbs
  turbo/generators/templates/component/package.json.hbs
  turbo/generators/templates/component/src/index.ts.hbs
  turbo/generators/templates/component/src/{{kebabCase componentName}}.tsx.hbs
  turbo/generators/templates/component/stories/{{kebabCase componentName}}.stories.tsx.hbs
  turbo/generators/templates/component/tsconfig.json.hbs
  turbo/generators/templates/component/tsup.config.ts.hbs
Labels: ⚙️ 세팅

#61 chore/#38 playwright 테스트 설정
  .github/workflows/chromatic_auto_deploy.yml
  .github/workflows/label-vrt-update.yml
  .github/workflows/pr-vrt.yml
  .gitignore
  .playwright/report/index.html
  .playwright/results.json
  .playwright/results/.last-run.json
  .playwright/results/components-Button-Button-컴포넌트-primary-시각적-회귀-테스트-chromium/Button-컴포넌트-primary-시각적-회귀-테스트-1-actual.png
  .playwright/results/components-Button-Button-컴포넌트-primary-시각적-회귀-테스트-firefox/Button-컴포넌트-primary-시각적-회귀-테스트-1-actual.png
  .playwright/results/components-Button-Button-컴포넌트-primary-시각적-회귀-테스트-webkit/Button-컴포넌트-primary-시각적-회귀-테스트-1-actual.png
  .playwright/snapshots/components/Button.test.ts-snapshots/Button-컴포넌트-primary-시각적-회귀-테스트-1-chromium-linux.png
  .playwright/snapshots/components/Button.test.ts-snapshots/Button-컴포넌트-primary-시각적-회귀-테스트-1-firefox-linux.png
  .playwright/snapshots/components/Button.test.ts-snapshots/Button-컴포넌트-primary-시각적-회귀-테스트-1-webkit-linux.png
  e2e/components/Button.test.ts
  e2e/test-utils/a11y.ts
  e2e/test-utils/storybook.ts
  package.json
  packages/primitive/components/Button.tsx
  playwright.config.ts
  tsconfig.json
Labels: ⚙️ 세팅

#56 feat/#51 공통 prettier 설정 불러오도록 설정 변경
  .vscode/settings.json
Labels: ⚙️ 세팅

#66 chore/#46 D-day Labeler workflow 추가
  .github/workflows/pr-dday-labeler.yml
Labels: ⚙️ 세팅, D-3
