Repository team-warrr/warrr-ui, pull requests merged in 2024-07, with the labels that each got.

#28 feat/#20 피그마 플러그인 보일러 플레이트 개발
  .vscode/settings.json
  packages/plugins/.gitkeep
  packages/plugins/boilerplate/.gitignore
  packages/plugins/boilerplate/figma.manifest.ts
  packages/plugins/boilerplate/index.html
  packages/plugins/boilerplate/injectBundledJsIntoHTML.ts
  packages/plugins/boilerplate/package.json
  packages/plugins/boilerplate/src/plugin/code.ts
  packages/plugins/boilerplate/src/shared/.gitkeep
  packages/plugins/boilerplate/src/ui/App.tsx
  packages/plugins/boilerplate/src/ui/main.tsx
  packages/plugins/boilerplate/tsconfig.json
  packages/plugins/boilerplate/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 🎯 기능 구현

#32 feat/#23 chromatic_auto_deploy workflow 추가
  .github/workflows/chromatic_auto_deploy.yml
  packages/primitive/components/Button.stories.ts
  packages/primitive/components/Button.tsx
  packages/primitive/components/Header.stories.ts
  packages/primitive/package.json
Labels: 🚀 배포

#33 chore/#30 devDependencies를 워크스페이스 레벨로 이동
  package.json
  packages/plugins/boilerplate/package.json
  packages/primitive/package.json
Labels: ⚙️ 세팅

#34 chore/#26 eslint, prettier, tsconfig 세팅
  .eslintrc.json
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  .prettierrc.json
  .vscode/settings.json
  package.json
  packages/plugins/boilerplate/.eslintrc.json
  packages/plugins/boilerplate/figma.manifest.ts
  packages/plugins/boilerplate/index.html
  packages/plugins/boilerplate/injectBundledJsIntoHTML.ts
  packages/plugins/boilerplate/package.json
  packages/plugins/boilerplate/src/ui/App.tsx
  packages/plugins/boilerplate/src/ui/main.tsx
  packages/plugins/boilerplate/tsconfig.json
  packages/plugins/boilerplate/vite.config.ts
  packages/primitive/.storybook/main.ts
  packages/primitive/components/Button.stories.ts
  packages/primitive/components/Button.tsx
  packages/primitive/components/Header.stories.ts
  packages/primitive/components/Header.tsx
  packages/primitive/components/button.css
  packages/primitive/components/header.css
  pnpm-lock.yaml
  tsconfig.json
Labels: ⚙️ 세팅
