Repository team-warrr/warrr-ui, pull requests merged in 2024-09, with the labels that each got.

#64 fix/#47 빌드 버그 해결
  packages/plugins/boilerplate/src/config/figma.manifest.ts
  packages/plugins/boilerplate/src/config/injectBundledJsIntoHTML.ts
  packages/plugins/boilerplate/tsconfig.json
  packages/plugins/boilerplate/vite.config.ts
  tsconfig.json
Labels: 🛠️ 버그 해결, D-2

#72 chore/#65 jest.setup.ts 설정
  jest.config.ts
  jest.setup.ts
  package.json
  packages/primitive/components/Button.test.tsx
  pnpm-lock.yaml
  tsconfig.json
Labels: D-1

#68 chore/#49 local github action test용 secret 파일 gitignore에 추가
  .gitignore
Labels: ⚙️ 세팅, D-1

#73 feat/#48 Divider 컴포넌트 개발
  .github/ISSUE_TEMPLATE/component-template.md
  packages/primitive/components/divider/README.md
  packages/primitive/components/divider/__tests__/divider.test.tsx
  packages/primitive/components/divider/package.json
  packages/primitive/components/divider/src/divider.tsx
  packages/primitive/components/divider/src/index.ts
  packages/primitive/components/divider/stories/divider.stories.tsx
  packages/primitive/components/divider/tsconfig.json
  packages/primitive/components/divider/tsup.config.ts
  pnpm-lock.yaml
Labels: 🎯 기능 구현, D-0

#90 feat/#50 github action 워크플로우 최적화
  .github/environments/versions.env
  .github/workflows/chromatic_auto_deploy.yml
  .github/workflows/label-vrt-update.yml
  .github/workflows/pr-vrt.yml
  scripts/.gitkeep
  scripts/install-dependencies.sh
  scripts/install-playwright.sh
  scripts/set-env.sh
Labels: 📈 성능 개선, D-0

#92 feat/#85 codegen에 e2e 테스트 코드 템플릿 생성 및 적용
  turbo/generators/config.ts
  turbo/generators/templates/e2e/test.ts.hbs
Labels: ⚙️ 세팅, D-0

#91 test/#84 Divider vrt 테스트 추가
  .playwright/results/components-Button-Button-컴포넌트-primary-시각적-회귀-테스트-chromium/Button-컴포넌트-primary-시각적-회귀-테스트-1-actual.png
  .playwright/results/components-Button-Button-컴포넌트-primary-시각적-회귀-테스트-firefox/Button-컴포넌트-primary-시각적-회귀-테스트-1-actual.png
  .playwright/results/components-Button-Button-컴포넌트-primary-시각적-회귀-테스트-webkit/Button-컴포넌트-primary-시각적-회귀-테스트-1-actual.png
  .playwright/snapshots/components/Button.test.ts-snapshots/Button-컴포넌트-primary-시각적-회귀-테스트-1-chromium-linux.png
  .playwright/snapshots/components/Button.test.ts-snapshots/Button-컴포넌트-primary-시각적-회귀-테스트-1-firefox-linux.png
  .playwright/snapshots/components/Button.test.ts-snapshots/Button-컴포넌트-primary-시각적-회귀-테스트-1-webkit-linux.png
  e2e/components/primitive/divider.test.ts
  packages/primitive/components/Button.stories.ts
  packages/primitive/components/Button.test.tsx
  packages/primitive/components/Button.tsx
  turbo/generators/config.ts
  turbo/generators/templates/e2e/test.ts.hbs
Labels: VRT, D-0

#112 chore/#93 husky 오류 해결
  .husky/pre-commit
  .husky/pre-push
  jest.config.ts
Labels: D-0
